//
// Module TUTORIAL.timer_tb.struct
//
// Created:
//          by - User.UNKNOWN (VBOX)
//          at - 14:26:24 23.04.2017
//
// Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
//

`resetall
`timescale 1ns/10ps
module timer_tb;


// Internal Declarations



// Local declarations

// Internal signal declarations
wire       alarm;
wire       clk;
wire [9:0] d;
wire [3:0] high;
wire [3:0] low;
wire       reset;
wire       start;
wire       stop;


// Instances 
timer U_0( 
   .clk   (clk), 
   .d     (d), 
   .reset (reset), 
   .start (start), 
   .stop  (stop), 
   .alarm (alarm), 
   .high  (high), 
   .low   (low)
); 

timer_tester U_1( 
   .alarm (alarm), 
   .high  (high), 
   .low   (low), 
   .clk   (clk), 
   .d     (d), 
   .reset (reset), 
   .start (start), 
   .stop  (stop)
); 


endmodule // timer_tb

