//
// Module timer_lib.timer.struct
//
// Created:
//          by - User.UNKNOWN (VBOX)
//          at - 15:54:54 27.04.2017
//
// Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
//

`resetall
`timescale 1ns/10ps
module timer( 
   clk, 
   d, 
   reset, 
   start, 
   stop, 
   alarm, 
   high, 
   low
);


// Internal Declarations

input        clk;
input  [9:0] d;
input        reset;
input        start;
input        stop;
output       alarm;
output [3:0] high;
output [3:0] low;


wire        clk;
wire [9:0]  d;
wire        reset;
wire        start;
wire        stop;
wire        alarm;
wire [3:0]  high;
wire [3:0]  low;

// Local declarations
reg[3:0] d_out;


// Non hierarchical truthtable declarations
 


// Internal signal declarations
wire       beep;
wire       clear;
wire [3:0] dat_in;
wire       hold;
wire       load;
wire       zero;


// Instances 
Control I0( 
   .clk   (clk), 
   .d     (d), 
   .reset (reset), 
   .start (start), 
   .stop  (stop), 
   .zero  (zero), 
   .beep  (beep), 
   .clear (clear), 
   .hold  (hold), 
   .load  (load)
); 

Counter I1( 
   .clear  (clear), 
   .clk    (clk), 
   .dat_in (dat_in), 
   .hold   (hold), 
   .load   (load), 
   .high   (high), 
   .low    (low), 
   .zero   (zero)
); 

// HDL Embedded Block 1 DtoB
// Non hierarchical truthtable
/////////////////////////////////////////////////////////////////
always @ (d) begin : dtob_truth_table_block_proc

   // Block 1
   if ((d[0] == 1))
      d_out = 4'b0000;
   else if ((d[1] == 1))
      d_out = 4'b0001;
   else if ((d[2] == 1))
      d_out = 4'b0010;
   else if ((d[3] == 1))
      d_out = 4'b0011;
   else if ((d[4] == 1))
      d_out = 4'b0100;
   else if ((d[5] == 1))
      d_out = 4'b0101;
   else if ((d[6] == 1))
      d_out = 4'b0110;
   else if ((d[7] == 1))
      d_out = 4'b0111;
   else if ((d[8] == 1))
      d_out = 4'b1000;
   else if ((d[9] == 1))
      d_out = 4'b1001;
   else
      d_out = 4'b0000;
end

// Concurrent statements
 assign dat_in = d_out;

// HDL Embedded Text Block 2 OR1
// OR1 2
assign alarm = hold | beep;                                       

endmodule // timer

